
"use client";

import Image from "next/image";
import { Button } from "./ui/button";
import { Download, Share2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

type GeneratedImageCardProps = {
    imageDataUri: string;
    prompt: string;
};

export function GeneratedImageCard({ imageDataUri, prompt }: GeneratedImageCardProps) {
    const { toast } = useToast();

    const handleDownload = () => {
        const link = document.createElement('a');
        link.href = imageDataUri;
        link.download = `${prompt.substring(0, 20).replace(/\s+/g, '_')}.png`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        toast({ title: "Image downloaded!" });
    };

    const handleShare = () => {
        if (navigator.share) {
            fetch(imageDataUri)
                .then(res => res.blob())
                .then(blob => {
                    const file = new File([blob], 'generated_image.png', { type: 'image/png' });
                    navigator.share({
                        title: 'Image from SearnAI',
                        text: `Image generated from prompt: "${prompt}"`,
                        files: [file],
                    }).catch(error => console.log('Error sharing', error));
                });
        } else {
            navigator.clipboard.writeText(imageDataUri);
            toast({ title: "Copied!", description: "Image data URL copied to clipboard." });
        }
    };

    return (
        <div className="w-full max-w-sm rounded-xl border bg-card/50 overflow-hidden">
            <div className="relative aspect-square">
                <Image 
                    src={imageDataUri}
                    alt={prompt}
                    fill
                    className="object-cover"
                />
            </div>
            <div className="p-3">
                <p className="font-semibold text-sm line-clamp-2">{prompt}</p>
                <p className="text-xs text-muted-foreground">Generated by Imagen</p>
                <div className="mt-3 flex gap-2">
                    <Button variant="outline" size="sm" className="w-full" onClick={handleDownload}>
                        <Download className="mr-2 h-4 w-4" />
                        Download
                    </Button>
                    <Button variant="ghost" size="icon" onClick={handleShare}>
                        <Share2 className="h-4 w-4" />
                    </Button>
                </div>
            </div>
        </div>
    );
}
